export enum FAVORITES_ACTION_TYPES {
    FETCH_FAVORITES_START = 'favorites/FETCH_FAVORITES_START',
    FETCH_FAVORITES_SUCCESS = 'favorites/FETCH_FAVORITES_SUCCESS',
    FETCH_FAVORITES_FAILED = 'favorites/FETCH_FAVORITES_FAILED',
    ADD_FAVORITE = 'favorites/ADD_FAVORITE',
};