export enum MOVIES_ACTION_TYPES {
    FETCH_MOVIES_START = 'movies/FETCH_MOVIES_START',
    FETCH_MOVIES_SUCCESS = 'movies/FETCH_MOVIES_SUCCESS',
    FETCH_RESULTS_SUCCESS = 'movies/FETCH_RESULTS_SUCCESS',
    FETCH_MOVIES_FAILED = 'movies/FETCH_MOVIES_FAILED',
};