export enum COMMENTS_ACTION_TYPES {
    FETCH_COMMENTS_START = 'comments/FETCH_COMMENTS_START',
    FETCH_COMMENTS_SUCCESS = 'comments/FETCH_COMMENTS_SUCCESS',
    FETCH_COMMENTS_FAILED = 'comments/FETCH_COMMENTS_FAILED',
  };