export enum MOVIE_ACTION_TYPES {
    FETCH_MOVIE_START = 'movie/FETCH_MOVIE_START',
    FETCH_MOVIE_SUCCESS = 'movie/FETCH_MOVIE_SUCCESS',
    FETCH_DIRECTORS_SUCCESS = 'movie/FETCH_DIRECTORS_SUCCESS',
    FETCH_ACTORS_SUCCESS = 'movie/FETCH_ACTORS_SUCCESS',
    FETCH_MOVIE_FAILED = 'movie/FETCH_MOVIE_FAILED',
};